param([Parameter(Mandatory=$true)][string]$InitialReceipt,[Parameter(Mandatory=$true)][string]$FinalReceipt,[Parameter(Mandatory=$true)][string]$Output)
$ErrorActionPreference='Stop'
if(Test-Path $Output){throw 'Preserve prior evidence; select a new output'}
$initial=Get-Content $InitialReceipt -Raw|ConvertFrom-Json;$final=Get-Content $FinalReceipt -Raw|ConvertFrom-Json
if(!$initial.ConDrvSuite -or !$final.ConDrvSuite -or $initial.State -ne 'Failed' -or $final.State -ne 'Failed' -or $final.SuiteResults.Count -ne 2){throw 'Require preserved complete ConDrv integration attempts'}
if([regex]::Matches($final.DriverOutput,'PASS unregistered static import fails before main').Count -ne 2 -or [regex]::Matches($final.DriverOutput,'PASS unregistered real Zig child fails before main').Count -ne 2 -or [regex]::Matches($final.DriverOutput,'PASS owned IFEO key absent after cleanup').Count -ne 2 -or [regex]::Matches($final.DriverOutput,'PASS owned Zig child IFEO absent after cleanup').Count -ne 2 -or $final.DriverOutput -notmatch 'PASS fresh deployment state restored'){throw 'Missing negative controls or actual cleanup'}
$rows=@()
foreach($row in $final.SuiteResults){
 $before=@($initial.SuiteResults|Where-Object {$_.Architecture -eq $row.Architecture})
 if($before.Count -ne 1 -or $before[0].Output -notmatch 'Case=profile-selected Pass=0' -or $row.Output -notmatch 'Case=profile-selected Pass=1' -or $row.Output -notmatch 'MappedImport Name=kxnt OriginalFirstThunk=' -or $row.Bindings -notmatch 'StaticBindingCount=26 Matches=26 EarlyKexDllLoaded=1 Result=PASS'){throw 'Missing mapped rewrite name and main import-slot proof'}
 foreach($case in @('profile-rewritten-basename','profile-native-basename','profile-basename-suffix-rejected','profile-extension-suffix-rejected','profile-basename-tail','profile-unterminated-tail')){if([regex]::Matches($row.Output,"Case=$case Pass=1").Count -ne 2){throw "Missing both PE-format boundary checks: $case"}}
 if($row.Output -notmatch 'PartialCompletion Injection=owned-KexDll-IAT Calls=6' -or $row.LookupControlOutput -notmatch 'Failures=0 Result=PASS'){throw 'Partial completion injection or native-route control failed'}
 $cold=[regex]::Match($row.Output,'Phase=0 NativeControl=0 HandleDelta=(-?\d+)');$control=[regex]::Match($row.LookupControlOutput,'Phase=0 NativeControl=1 HandleDelta=(-?\d+)')
 if(!$cold.Success -or !$control.Success -or $cold.Groups[1].Value -ne $control.Groups[1].Value -or $row.Output -notmatch 'Phase=1 NativeControl=0 HandleDelta=0' -or $row.LookupControlOutput -notmatch 'Phase=1 NativeControl=1 HandleDelta=0' -or $row.Output -notmatch 'Case=concurrent-handle-identities Pass=1'){throw 'Resource gate failed'}
 $failed=@([regex]::Matches($row.Output,'Case=(\S+) Pass=0')|ForEach-Object {$_.Groups[1].Value})
 if($row.Architecture -eq 'x86'){if($failed.Count -or !$row.Passed){throw 'WOW64 full integration failed'}}
 else{if($failed.Count -ne 4 -or @($failed|Where-Object {$_ -notin @('zig-console-exit','zig-console-content')}).Count -or $row.Passed){throw 'Unexpected x64 failure scope'}}
 $rows+=[pscustomobject]@{Architecture=$row.Architecture;MainProfileSelected=$true;MainValueAndBoundaryChecksPassed=$true;PartialInjectedCalls=6;ColdDelta=[int]$cold.Groups[1].Value;NativeControlColdDelta=[int]$control.Groups[1].Value;WarmDelta=0;UnprofiledControlPassed=$true;MainStaticSlots=26;Passed=$row.Passed;RemainingFailedCases=$failed;RealZigRedirectedSuccesses=[regex]::Matches($row.Output,'ZigRedirect Pipe=[01] Exit=00000000 Bytes=40').Count;RealZigConsoleSuccesses=[regex]::Matches($row.Output,'ZigConsole Exit=00000000 ReadUnits=39').Count}
}
[pscustomobject]@{InitialReceiptSHA256=(Get-FileHash $InitialReceipt).Hash;FinalReceiptSHA256=(Get-FileHash $FinalReceipt).Hash;AnalyzerSHA256=(Get-FileHash $PSCommandPath).Hash;Results=$rows;Interpretation='Production content profile now recognizes exact bounded extensionless names emitted by normal DLL rewriting. WOW64 full integration passed. x64 main console/file/pipe/partial/boundary/concurrency tests passed, but real Zig child console exit/content failed twice. Do not declare full native-x64 integration or reinterpret the Failed receipt as Passed. Ambiguous console/File aliases, child profile state and import rewriting remain possible causes until measured.'}|ConvertTo-Json -Depth 8|Set-Content $Output -Encoding UTF8
